# Generated by Django 3.2.9 on 2021-11-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hien Thi'), (0, 'An')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(choices=[]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Hien Thi'), (0, 'An')]),
        ),
    ]
